export const PLAYER_MIN_ATTACK = 10;
export const PLAYER_MAX_ATTACK = 75;

export const PLAYER_START_LIFE_POINTS = 2000;
export const PLAYER_START_MANA_POINTS = 100;

export const WARRIOR_ADD_HEALTH_PER_LEVEL = 75;
export const WARRIOR_REGENERATE_HEALTH_EACH_ROUND = 15;
export const WARRIOR_ADD_MANA_PER_LEVEL = 75;
export const WARRIOR_REGENERATE_MANA_EACH_ROUND = 5;

export const MAGE_ADD_HEALTH_PER_LEVEL = 25;
export const MAGE_REGENERATE_HEALTH_EACH_ROUND = 5;
export const MAGE_ADD_MANA_PER_LEVEL = 75;
export const MAGE_REGENERATE_MANA_EACH_ROUND = 15;

export const ARCHER_ADD_HEALTH_PER_LEVEL = 50;
export const ARCHER_REGENERATE_HEALTH_EACH_ROUND = 10;
export const ARCHER_ADD_MANA_PER_LEVEL = 50;
export const ARCHER_REGENERATE_MANA_EACH_ROUND = 10;

export const HEALTH_POTION_PRICE = 50;
export const MANA_POTION_PRICE = 50;

export const ORC_HEALTH_POINTS = 100;
export const ORC_MIN_ATTACK = 15;
export const ORC_MAX_ATTACK = 50;
export const ORC_EXPERIENCE_FOR_KILL = 50;
export const ORC_MIN_LOOT = 25;
export const ORC_MAX_LOOT = 100;

export const WEREWOLF_HEALTH_POINTS = 200;
export const WEREWOLF_MIN_ATTACK = 25;
export const WEREWOLF_MAX_ATTACK = 75;
export const WEREWOLF_EXPERIENCE_FOR_KILL = 100;
export const WEREWOLF_MIN_LOOT = 100;
export const WEREWOLF_MAX_LOOT = 150;

export const VAMPIRE_HEALTH_POINTS = 350;
export const VAMPIRE_MIN_ATTACK = 35;
export const VAMPIRE_MAX_ATTACK = 125;
export const VAMPIRE_EXPERIENCE_FOR_KILL = 200;
export const VAMPIRE_MIN_LOOT = 70;
export const VAMPIRE_MAX_LOOT = 50;

export const DRAGON_HEALTH_POINTS = 250;
export const DRAGON_MIN_ATTACK = 50;
export const DRAGON_MAX_ATTACK = 200;
export const DRAGON_EXPERIENCE_FOR_KILL = 500;
export const DRAGON_MIN_LOOT = 125;
export const DRAGON_MAX_LOOT = 250;

export const FERUMBRAS_HEALTH_POINTS = 1000;
export const FERUMBRAS_MIN_ATTACK = 15;
export const FERUMBRAS_MAX_ATTACK = 100;
export const FERUMBRAS_EXPERIENCE_FOR_KILL = 1000;
export const FERUMBRAS_MIN_LOOT = 350;
export const FERUMBRAS_MAX_LOOT = 500;
